// ── Devashri Builders — Global Datastore ──

window.plotsData = [
  {
    id: 'kashiPuram-001',
    phase: 1,
    name: 'Kashi Puram Green City – Plot A15',
    name_hi: 'काशी पुरम ग्रीन सिटी – प्लॉट A15',
    project: 'Kashi Puram Green City',
    project_hi: 'काशी पुरम ग्रीन सिटी',
    location: 'Chopan-Sindhuriya Marg, Sonbhadra',
    location_hi: 'चोपन-सिंदुरिया मार्ग, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    area: 1350,
    dimensions: '27×50',
    pricePerSqft: 599,
    totalPrice: 808650,
    status: 'available',
    featured: true,
    rera: '',
    facing: 'East',
    facing_hi: 'पूर्व',
    category: 'residential',
    category_hi: 'आवासीय',
    amenities: ['25 Ft Wide Road', 'Sewage System', 'Water Supply', 'Street Lights', 'Security'],
    amenities_hi: ['25 फीट चौड़ी सड़क', 'सीवेज प्रणाली', 'जलापूर्ति', 'स्ट्रीट लाइट्स', 'सुरक्षा'],
    nearby: [
      { label: 'Chopan Hospital', label_hi: 'चोपन अस्पताल', distance: '500 m' },
      { label: 'Varanasi-Shaktinagar Hwy', label_hi: 'वाराणसी-शक्तिनगर हाईवे', distance: '800 m' },
      { label: 'Obra Marg', label_hi: 'ओबरा मार्ग', distance: '100 m' },
      { label: 'Govt School', label_hi: 'सरकारी स्कूल', distance: '1.2 km' },
    ],
    paymentPlans: [
      { name: 'Easy Installment', name_hi: 'आसान किस्त योजना', description: '50% booking amount, balance in 24 months', description_hi: '50% बुकिंग राशि, शेष 24 महीनों में' },
      { name: 'Full Payment', name_hi: 'पूर्ण भुगतान', description: 'One-time payment with 3% additional discount', description_hi: '3% अतिरिक्त छूट के साथ एकमुश्त भुगतान' },
      { name: 'Bank Loan', name_hi: 'बैंक ऋण', description: 'Assistance with SBI & HDFC home loans available', description_hi: 'एसबीआई और एचडीएफसी गृह ऋण में सहायता उपलब्ध' },
    ],
    images: [
      'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Premium residential plot in the heart of Kashi Puram Green City. Situated on Chopan-Sindhuriya Marg, this plot offers peaceful surroundings with all modern civic amenities. Ideal for building your dream home in a clean, green environment in Sonbhadra.',
    description_hi: 'काशी पुरम ग्रीन सिटी के केंद्र में प्रीमियम आवासीय प्लॉट। चोपन-सिंदुरिया मार्ग पर स्थित, यह प्लॉट सभी आधुनिक नागरिक सुविधाओं के साथ शांतिपूर्ण वातावरण प्रदान करता है। सोनभद्र में एक स्वच्छ, हरित वातावरण में अपने सपनों का घर बनाने के लिए आदर्श।',
    highlights: ['Clear Title', 'NA Order Obtained', '25 Ft Internal Roads', 'Borewell Water at 60 Ft'],
    highlights_hi: ['स्पष्ट विलेख/शीर्षक', 'गैर-कृषि (NA) आदेश प्राप्त', '25 फीट आंतरिक सड़कें', '60 फीट पर बोरवेल पानी उपलब्ध'],
  },
  {
    id: 'kashiPuram-002',
    phase: 1,
    name: 'Kashi Puram Green City – Plot B22',
    name_hi: 'काशी पुरम ग्रीन सिटी – प्लॉट B22',
    project: 'Kashi Puram Green City',
    project_hi: 'काशी पुरम ग्रीन सिटी',
    location: 'Chopan-Sindhuriya Marg, Sonbhadra',
    location_hi: 'चोपन-सिंदुरिया मार्ग, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    area: 1350,
    dimensions: '27×50',
    pricePerSqft: 599,
    totalPrice: 808650,
    status: 'reserved',
    featured: false,
    rera: '',
    facing: 'West',
    facing_hi: 'पश्चिम',
    category: 'residential',
    category_hi: 'आवासीय',
    amenities: ['25 Ft Wide Road', 'Sewage System', 'Water Supply', 'Street Lights'],
    amenities_hi: ['25 फीट चौड़ी सड़क', 'सीवेज प्रणाली', 'जलापूर्ति', 'स्ट्रीट लाइट्स'],
    nearby: [
      { label: 'Chopan Hospital', label_hi: 'चोपन अस्पताल', distance: '500 m' },
      { label: 'Varanasi-Shaktinagar Hwy', label_hi: 'वाराणसी-शक्तिनगर हाईवे', distance: '800 m' },
    ],
    paymentPlans: [
      { name: 'Easy Installment', name_hi: 'आसान किस्त योजना', description: '50% booking amount, balance in 24 months', description_hi: '50% बुकिंग राशि, शेष 24 महीनों में' },
      { name: 'Full Payment', name_hi: 'पूर्ण भुगतान', description: 'One-time with 3% discount', description_hi: '3% छूट के साथ एकमुश्त भुगतान' },
    ],
    images: [
      'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'West-facing residential plot in Kashi Puram Green City with excellent connectivity to Varanasi-Shaktinagar highway.',
    description_hi: 'काशी पुरम ग्रीन सिटी में पश्चिम-मुखी आवासीय प्लॉट, जो वाराणसी-शक्तिनगर राजमार्ग से उत्कृष्ट कनेक्टिविटी प्रदान करता है।',
    highlights: ['Clear Title', '25 Ft Internal Roads', 'NA Order Obtained'],
    highlights_hi: ['स्पष्ट विलेख/शीर्षक', '25 फीट आंतरिक सड़कें', 'गैर-कृषि (NA) आदेश प्राप्त'],
  },
  {
    id: 'vinayakPuram-001',
    phase: 1,
    name: 'Vinayak Puram Colony – Plot 15',
    name_hi: 'विनायक पुरम कॉलोनी – प्लॉट 15',
    project: 'Vinayak Puram Society',
    project_hi: 'विनायक पुरम सोसाइटी',
    location: 'Robertsganj, Sonbhadra',
    location_hi: 'रॉबर्ट्सगंज, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    area: 1500,
    dimensions: '25×60',
    pricePerSqft: 699,
    totalPrice: 1048500,
    status: 'available',
    featured: true,
    rera: '',
    facing: 'North',
    facing_hi: 'उत्तर',
    category: 'residential',
    category_hi: 'आवासीय',
    amenities: ['20 Ft Wide Road', 'Street Lights', 'Govt Road Access', 'Clear Boundaries'],
    amenities_hi: ['20 फीट चौड़ी सड़क', 'स्ट्रीट लाइट्स', 'सरकारी सड़क पहुंच', 'स्पष्ट सीमाएं'],
    nearby: [
      { label: 'Sant Kanaram School', label_hi: 'संत कानाराम स्कूल', distance: '2 km' },
      { label: 'Aayush Hospital', label_hi: 'आयुष अस्पताल', distance: '1.5 km' },
      { label: 'FCI Godown', label_hi: 'एफसीआई गोदाम', distance: '300 m' },
      { label: 'Main Road', label_hi: 'मुख्य सड़क', distance: '50 m' },
    ],
    paymentPlans: [
      { name: 'Installment Plan', name_hi: 'किस्त योजना', description: '50% booking, 24 months EMI', description_hi: '50% बुकिंग, 24 महीने ईएमआई' },
      { name: 'Full Payment', name_hi: 'पूर्ण भुगतान', description: 'Upfront payment with registry assistance', description_hi: 'रजिस्ट्री सहायता के साथ अग्रिम भुगतान' },
    ],
    images: [
      'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Affordable residential plot in Vinayak Puram Colony, Sonbhadra. Government road access, wide internal streets, and proximity to essential services make this an ideal investment.',
    description_hi: 'विनायक पुरम कॉलोनी, सोनभद्र में किफायती आवासीय प्लॉट। सरकारी सड़क पहुंच, चौड़ी आंतरिक गलियां और आवश्यक सेवाओं से निकटता इसे एक आदर्श निवेश बनाती है।',
    highlights: ['Govt Road Touch', 'Wide Internal Roads', 'Clear Title', 'EMI Available'],
    highlights_hi: ['सरकारी सड़क से लगा हुआ', 'चौड़ी आंतरिक सड़कें', 'स्पष्ट विलेख/शीर्षक', 'किस्त (EMI) सुविधा उपलब्ध'],
  },
  {
    id: 'vinayakPuram-002',
    phase: 1,
    name: 'Vinayak Puram Colony – Plot 28',
    name_hi: 'विनायक पुरम कॉलोनी – प्लॉट 28',
    project: 'Vinayak Puram Society',
    project_hi: 'विनायक पुरम सोसाइटी',
    location: 'Robertsganj, Sonbhadra',
    location_hi: 'रॉबर्ट्सगंज, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    area: 1500,
    dimensions: '25×60',
    pricePerSqft: 699,
    totalPrice: 1048500,
    status: 'available',
    featured: false,
    rera: '',
    facing: 'South',
    facing_hi: 'दक्षिण',
    category: 'residential',
    category_hi: 'आवासीय',
    amenities: ['20 Ft Wide Road', 'Street Lights', 'Govt Road Access'],
    amenities_hi: ['20 फीट चौड़ी सड़क', 'स्ट्रीट लाइट्स', 'सरकारी सड़क पहुंच'],
    nearby: [
      { label: 'Sant Kanaram School', label_hi: 'संत कानाराम स्कूल', distance: '2 km' },
      { label: 'Aayush Hospital', label_hi: 'आयुष अस्पताल', distance: '1.5 km' },
    ],
    paymentPlans: [
      { name: 'Installment Plan', name_hi: 'किस्त योजना', description: '50% booking, 24 months EMI', description_hi: '50% बुकिंग, 24 महीने ईएमआई' },
    ],
    images: [
      'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'South-facing plot in Vinayak Puram Colony with excellent road access and clear title.',
    description_hi: 'विनायक पुरम कॉलोनी में दक्षिण-मुखी प्लॉट, बेहतरीन सड़क पहुंच और स्पष्ट विलेख/शीर्षक के साथ।',
    highlights: ['Govt Road Touch', 'Wide Internal Roads', 'Clear Title'],
    highlights_hi: ['सरकारी सड़क से लगा हुआ', 'चौड़ी आंतरिक सड़कें', 'स्पष्ट विलेख/शीर्षक'],
  },
  {
    id: 'bichchhi-001',
    phase: 1,
    name: 'Bichchhi Layout – Plot 05',
    name_hi: 'बिछी लेआउट – प्लॉट 05',
    project: 'Bichchhi Residential Layout',
    project_hi: 'बिछी आवासीय लेआउट',
    location: 'Bichchhi, Varanasi-Shaktinagar Highway, Sonbhadra',
    location_hi: 'बिछी, वाराणसी-शक्तिनगर हाईवे, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    area: 1800,
    dimensions: '30×60',
    pricePerSqft: 1051,
    totalPrice: 1891800,
    status: 'available',
    featured: true,
    rera: '',
    facing: 'East',
    facing_hi: 'पूर्व',
    category: 'residential',
    category_hi: 'आवासीय',
    amenities: ['20 Ft Wide Road', 'Govt Road Access', 'Corner Plot', 'Prime Location'],
    amenities_hi: ['20 फीट चौड़ी सड़क', 'सरकारी सड़क पहुंच', 'कोने का प्लॉट', 'प्रमुख स्थान'],
    nearby: [
      { label: 'Varanasi-Shaktinagar Highway', label_hi: 'वाराणसी-शक्तिनगर हाईवे', distance: 'Direct Access' },
      { label: 'Bichchhi Market', label_hi: 'बिछी बाजार', distance: '200 m' },
      { label: 'Govt Hospital', label_hi: 'सरकारी अस्पताल', distance: '1.8 km' },
    ],
    paymentPlans: [
      { name: 'Direct Registration', name_hi: 'तत्काल रजिस्ट्री', description: 'Full payment with immediate registry', description_hi: 'पूर्ण भुगतान के साथ तत्काल रजिस्ट्री' },
      { name: 'Loan Assistance', name_hi: 'ऋण सहायता', description: 'Bank loan tie-up available', description_hi: 'बैंक ऋण सुविधा उपलब्ध' },
    ],
    images: [
      'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Prime corner plot on the Varanasi-Shaktinagar Highway at Bichchhi. Excellent location with direct highway access, perfect for long-term investment and residential use.',
    description_hi: 'बिछी में वाराणसी-शक्तिनगर हाईवे पर प्राइम कॉर्नर प्लॉट। सीधे हाईवे पहुंच के साथ बेहतरीन स्थान, दीर्घकालिक निवेश और आवासीय उपयोग के लिए उपयुक्त।',
    highlights: ['Highway Frontage', 'Corner Plot', 'Govt Road Access', 'High Appreciation'],
    highlights_hi: ['हाईवे फ्रंट व्यू', 'कोने का प्लॉट', 'सरकारी सड़क पहुंच', 'उच्च मूल्य वृद्धि क्षमता'],
  },
  {
    id: 'bichchhi-002',
    phase: 1,
    name: 'Bichchhi Layout – Plot 08',
    name_hi: 'बिछी लेआउट – प्लॉट 08',
    project: 'Bichchhi Residential Layout',
    project_hi: 'बिछी आवासीय लेआउट',
    location: 'Bichchhi, Varanasi-Shaktinagar Highway, Sonbhadra',
    location_hi: 'बिछी, वाराणसी-शक्तिनगर हाईवे, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    area: 1500,
    dimensions: '25×60',
    pricePerSqft: 1051,
    totalPrice: 1576500,
    status: 'sold',
    featured: false,
    rera: '',
    facing: 'West',
    facing_hi: 'पश्चिम',
    category: 'residential',
    category_hi: 'आवासीय',
    amenities: ['20 Ft Wide Road', 'Govt Road Access'],
    amenities_hi: ['20 फीट चौड़ी सड़क', 'सरकारी सड़क पहुंच'],
    nearby: [
      { label: 'Varanasi-Shaktinagar Highway', label_hi: 'वाराणसी-शक्तिनगर हाईवे', distance: 'Direct Access' },
    ],
    paymentPlans: [],
    images: [
      'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Residential plot on Varanasi-Shaktinagar Highway. Already sold.',
    description_hi: 'वाराणसी-शक्तिनगर हाईवे पर आवासीय प्लॉट। पहले ही बिक चुका है।',
    highlights: ['Highway Frontage', 'Govt Road Access'],
    highlights_hi: ['हाईवे फ्रंट व्यू', 'सरकारी सड़क पहुंच'],
  },
  {
    id: 'greenValley-001',
    phase: 2,
    name: 'Green Valley Enclave – Plot C12',
    name_hi: 'ग्रीन वैली एन्क्लेव – प्लॉट C12',
    project: 'Green Valley Enclave',
    project_hi: 'ग्रीन वैली एन्क्लेव',
    location: 'Mirzapur Road, Mirzapur',
    location_hi: 'मिर्जापुर रोड, मिर्जापुर',
    city: 'Mirzapur',
    city_hi: 'मिर्जापुर',
    area: 1200,
    dimensions: '30×40',
    pricePerSqft: 750,
    totalPrice: 900000,
    status: 'available',
    featured: true,
    rera: '',
    facing: 'East',
    facing_hi: 'पूर्व',
    category: 'residential',
    category_hi: 'आवासीय',
    amenities: ['Gated Community', 'Club House', 'Water Supply', 'Wide Roads', 'Street Lights'],
    amenities_hi: ['गेटेड कम्युनिटी', 'क्लब हाउस', 'जलापूर्ति', 'चौड़ी सड़कें', 'स्ट्रीट लाइट्स'],
    nearby: [
      { label: 'Mirzapur Railway Station', label_hi: 'मिर्जापुर रेलवे स्टेशन', distance: '3.5 km' },
      { label: 'District Hospital', label_hi: 'जिला अस्पताल', distance: '2.0 km' },
      { label: 'Mirzapur Hwy Bypass', label_hi: 'मिर्जापुर हाईवे बाईपास', distance: '500 m' },
    ],
    paymentPlans: [
      { name: 'Pre-launch Installment', name_hi: 'प्री-लॉन्च किस्त योजना', description: '40% booking amount, balance in 18 months', description_hi: '40% बुकिंग राशि, शेष 18 महीनों में' },
      { name: 'Cash Discount', name_hi: 'नकद छूट योजना', description: 'One-time payment with 4% discount', description_hi: '4% छूट के साथ एकमुश्त भुगतान' },
    ],
    images: [
      'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Premium pre-launch residential plot in Green Valley Enclave, Mirzapur. Offering state of the art gated community infrastructure with club house, landscaped parks, and wide internal roads.',
    description_hi: 'ग्रीन वैली एन्क्लेव, मिर्जापुर में प्रीमियम प्री-लॉन्च आवासीय प्लॉट। क्लब हाउस, सुंदर पार्कों और चौड़ी आंतरिक सड़कों के साथ अत्याधुनिक गेटेड कम्युनिटी इंफ्रास्ट्रक्चर की पेशकश।',
    highlights: ['Pre-launch Pricing', 'Registry Clearances Underway', 'Club House Access', 'Gated Security'],
    highlights_hi: ['प्री-लॉन्च विशेष दर', 'रजिस्ट्री मंजूरी प्रक्रिया जारी', 'क्लब हाउस की पहुंच', 'गेटेड सुरक्षा'],
  }
];

window.projectsData = [
  {
    id: 'kashi-puram',
    phase: 1,
    name: 'Kashi Puram Green City',
    name_hi: 'काशी पुरम ग्रीन सिटी',
    location: 'Chopan-Sindhuriya Marg, Sonbhadra',
    location_hi: 'चोपन-सिंदुरिया मार्ग, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    status: 'ongoing',
    status_hi: 'चल रही है',
    totalPlots: 120,
    availablePlots: 48,
    priceRange: '₹599/sqft',
    priceRange_hi: '₹599/वर्ग फुट',
    plotSizes: '27×50, 27×55 sq ft',
    plotSizes_hi: '27×50, 27×55 वर्ग फुट',
    area: '10 acres',
    area_hi: '10 एकड़',
    launchDate: 'March 2024',
    launchDate_hi: 'मार्च 2024',
    highlights: ['25 Ft Roads', 'Sewage System', 'Water at 60 Ft', 'NA Cleared'],
    highlights_hi: ['25 फीट सड़कें', 'सीवेज सिस्टम', '60 फीट पर पानी', 'एनए (NA) स्वीकृत'],
    image: 'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A thoughtfully planned residential township on Chopan-Sindhuriya Marg offering affordable premium plots with all amenities. Close to Varanasi-Shaktinagar highway and Chopan Hospital.',
    description_hi: 'चोपन-सिंदुरिया मार्ग पर सोच-समझकर बनाई गई आवासीय टाउनशिप जो सभी सुविधाओं के साथ किफायती प्रीमियम प्लॉट प्रदान करती है। वाराणसी-शक्तिनगर राजमार्ग और चोपन अस्पताल के करीब।',
  },
  {
    id: 'vinayak-puram',
    phase: 1,
    name: 'Vinayak Puram Society',
    name_hi: 'विनायक पुरम सोसाइटी',
    location: 'Robertsganj, Sonbhadra',
    location_hi: 'रॉबर्ट्सगंज, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    status: 'ongoing',
    status_hi: 'चल रही है',
    totalPlots: 80,
    availablePlots: 32,
    priceRange: '₹699/sqft',
    priceRange_hi: '₹699/वर्ग फुट',
    plotSizes: '25×60, 25×55 sq ft',
    plotSizes_hi: '25×60, 25×55 वर्ग फुट',
    area: '7 acres',
    area_hi: '7 एकड़',
    launchDate: 'January 2024',
    launchDate_hi: 'जनवरी 2024',
    highlights: ['Govt Road Touch', '20 Ft Internal Roads', 'Clear Title', 'EMI Available'],
    highlights_hi: ['सरकारी सड़क से लगा', '20 फीट आंतरिक सड़कें', 'स्पष्ट विलेख', 'ईएमआई सुविधा'],
    image: 'https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Government road-facing layout in the heart of Robertsganj. All plots have direct road access, clear titles, and flexible EMI options. Perfect for families and investors alike.',
    description_hi: 'रॉबर्ट्सगंज के मध्य में सरकारी सड़क के सामने का लेआउट। सभी भूखंडों में सीधी सड़क पहुंच, स्पष्ट विलेख और लचीले ईएमआई विकल्प हैं। परिवारों और निवेशकों दोनों के लिए बिल्कुल सही।',
  },
  {
    id: 'bichchhi-layout',
    phase: 1,
    name: 'Bichchhi Residential Layout',
    name_hi: 'बिछी आवासीय लेआउट',
    location: 'Bichchhi, Varanasi-Shaktinagar Highway, Sonbhadra',
    location_hi: 'बिछी, वाराणसी-शक्तिनगर हाईवे, सोनभद्र',
    city: 'Sonbhadra',
    city_hi: 'सोनभद्र',
    status: 'ongoing',
    status_hi: 'चल रही है',
    totalPlots: 45,
    availablePlots: 12,
    priceRange: '₹1,051/sqft',
    priceRange_hi: '₹1,051/वर्ग फुट',
    plotSizes: '25×60, 30×60 sq ft',
    plotSizes_hi: '25×60, 30×60 वर्ग फुट',
    area: '5 acres',
    area_hi: '5 एकड़',
    launchDate: 'September 2023',
    launchDate_hi: 'सितंबर 2023',
    highlights: ['Highway Frontage', 'Corner Plots Available', 'High Appreciation', 'Registry Ready'],
    highlights_hi: ['हाईवे फ्रंट व्यू', 'कॉर्नर प्लॉट उपलब्ध', 'उच्च मूल्य वृद्धि', 'रजिस्ट्री के लिए तैयार'],
    image: 'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Premium plots directly on the Varanasi-Shaktinagar Highway at Bichchhi. Ideal for both residential and commercial investment with guaranteed high appreciation.',
    description_hi: 'बिछी में सीधे वाराणसी-शक्तिनगर हाईवे पर प्रीमियम प्लॉट। आवासीय और वाणिज्यिक दोनों निवेशों के लिए आदर्श, उच्च मूल्य वृद्धि की गारंटी के साथ।',
  },
  {
    id: 'green-valley',
    phase: 2,
    name: 'Green Valley Enclave',
    name_hi: 'ग्रीन वैली एन्क्लेव',
    location: 'Mirzapur Road, Mirzapur',
    location_hi: 'मिर्जापुर रोड, मिर्जापुर',
    city: 'Mirzapur',
    city_hi: 'मिर्जापुर',
    status: 'upcoming',
    status_hi: 'नया लॉन्च',
    totalPlots: 200,
    availablePlots: 200,
    priceRange: '₹750/sqft (Pre-launch)',
    priceRange_hi: '₹750/वर्ग फुट (लॉन्च से पहले)',
    plotSizes: '30×50, 40×60 sq ft',
    plotSizes_hi: '30×50, 40×60 वर्ग फुट',
    area: '18 acres',
    area_hi: '18 एकड़',
    launchDate: 'August 2025',
    launchDate_hi: 'अगस्त 2025',
    highlights: ['Pre-launch Pricing', 'Gated Community', 'Club House', 'Registry Clearances Underway'],
    highlights_hi: ['लॉन्च पूर्व विशेष दर', 'गेटेड कम्युनिटी', 'क्लब हाउस', 'रजिस्ट्री मंजूरी जारी'],
    image: 'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Our flagship upcoming project — a fully gated residential enclave on Mirzapur Road with club house, landscaped parks, and premium internal infrastructure. Pre-launch bookings open.',
    description_hi: 'हमारी आगामी प्रमुख परियोजना — क्लब हाउस, सुंदर उद्यानों और प्रीमियम आंतरिक बुनियादी ढांचे के साथ मिर्जापुर रोड पर एक पूर्णतः गेटेड आवासीय एन्क्लेव। प्री-लॉन्च बुकिंग शुरू।',
  },
  {
    id: 'surya-nagar',
    phase: 2,
    name: 'Surya Nagar Colony',
    name_hi: 'सूर्य नगर कॉलोनी',
    location: 'Chunar Road, Mirzapur',
    location_hi: 'चुनार रोड, मिर्जापुर',
    city: 'Mirzapur',
    city_hi: 'मिर्जापुर',
    status: 'completed',
    status_hi: 'पूर्ण',
    totalPlots: 60,
    availablePlots: 0,
    priceRange: '₹420–480/sqft',
    priceRange_hi: '₹420–480/वर्ग फुट',
    plotSizes: '25×50 sq ft',
    plotSizes_hi: '25×50 वर्ग फुट',
    area: '4 acres',
    area_hi: '4 एकड़',
    launchDate: 'October 2022',
    launchDate_hi: 'अक्टूबर 2022',
    highlights: ['Fully Sold Out', 'All Registries Done', 'Community Built'],
    highlights_hi: ['पूर्णतः बिक चुका है', 'सभी रजिस्ट्रियां पूर्ण', 'समुदाय निर्मित'],
    image: 'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Successfully completed residential layout at Chunar Road, Mirzapur. All 60 plots sold, registered, and handed over. A testament to our commitment to on-time delivery.',
    description_hi: 'चुनार रोड, मिर्जापुर में सफलतापूर्वक पूर्ण हुआ आवासीय लेआउट। सभी 60 भूखंड बिक गए, पंजीकृत हुए और सौंपे गए। समय पर वितरण के प्रति हमारी प्रतिबद्धता का प्रमाण।',
  },
];

window.blogPostsData = [
  {
    id: '1',
    title: '5 Things to Check Before Buying a Plot in UP',
    title_hi: 'यूपी में प्लॉट खरीदने से पहले चेक करने योग्य 5 बातें',
    slug: '5-things-to-check-before-buying-plot-up',
    excerpt: 'From legal verification to soil testing — here is a practical checklist every first-time plot buyer in Uttar Pradesh should go through before signing any documents.',
    excerpt_hi: 'कानूनी सत्यापन से लेकर मिट्टी के परीक्षण तक — उत्तर प्रदेश में पहली बार प्लॉट खरीदने वाले प्रत्येक व्यक्ति के लिए कोई भी दस्तावेज हस्ताक्षर करने से पहले की व्यावहारिक चेकलिस्ट।',
    category: 'Buyer Guide',
    category_hi: 'क्रेता गाइड',
    readTime: 5,
    date: 'April 12, 2025',
    date_hi: '12 अप्रैल, 2025',
    author: 'Rajesh Verma',
    author_hi: 'राजेश वर्मा',
    image: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['buyer guide', 'legal', 'UP'],
  },
  {
    id: '2',
    title: 'Why Sonbhadra & Mirzapur Outskirts Are the Next Big Investment Zone',
    title_hi: 'सोनभद्र और मिर्जापुर के बाहरी इलाके अगले बड़े निवेश क्षेत्र क्यों बन रहे हैं',
    slug: 'varanasi-outskirts-investment-zone',
    excerpt: 'Infrastructure growth, highway expansion, and rising demand from NRIs are making Sonbhadra\'s peripheral areas some of the most attractive land investment destinations.',
    excerpt_hi: 'बुनियादी ढांचे का विकास, राजमार्गों का विस्तार और एनआरआई की बढ़ती मांग सोनभद्र के बाहरी क्षेत्रों को सबसे आकर्षक भूमि निवेश स्थलों में से एक बना रही है।',
    category: 'Location Analysis',
    category_hi: 'स्थान विश्लेषण',
    readTime: 7,
    date: 'March 28, 2025',
    date_hi: '28 मार्च, 2025',
    author: 'Priya Singh',
    author_hi: 'प्रिया सिंह',
    image: 'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['investment', 'sonbhadra', 'location'],
  },
  {
    id: '3',
    title: 'Understanding Legal Clearances for Plot Buyers: A Simple Guide',
    title_hi: 'प्लॉट खरीदारों के लिए कानूनी मंजूरियों को समझना: एक सरल मार्गदर्शिका',
    slug: 'understanding-legal-clearances-plot-buyers',
    excerpt: 'Legal protections extend to plot buyers too. Learn what verified land documents mean, what papers to verify, and how to check land titles online.',
    excerpt_hi: 'कानूनी सुरक्षा प्लॉट खरीदारों पर भी लागू होती है। जानें कि सत्यापित भूमि दस्तावेजों का क्या अर्थ है, किन कागजात को सत्यापित करना है, और ऑनलाइन भूमि शीर्षक कैसे जांचें।',
    category: 'Legal Guide',
    category_hi: 'कानूनी गाइड',
    readTime: 6,
    date: 'February 15, 2025',
    date_hi: '15 फरवरी, 2025',
    author: 'Amit Tiwari',
    author_hi: 'अमित तिवारी',
    image: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['legal', 'documentation'],
  },
  {
    id: '4',
    title: 'Plot vs Flat: Which is the Smarter Investment in 2025?',
    title_hi: 'प्लॉट बनाम फ्लैट: 2025 में कौन सा अधिक स्मार्ट निवेश है?',
    slug: 'plot-vs-flat-smarter-investment-2025',
    excerpt: 'Comparing appreciation rates, rental yields, liquidity, and long-term value — a data-driven look at why plots consistently outperform flats for wealth creation.',
    excerpt_hi: 'मूल्य वृद्धि दर, किराये की उपज, तरलता और दीर्घकालिक मूल्य की तुलना — एक डेटा-संचालित विश्लेषण कि संपत्ति निर्माण के लिए भूखंड फ्लैटों से लगातार बेहतर प्रदर्शन क्यों करते हैं।',
    category: 'Investment Insight',
    category_hi: 'निवेश अंतर्दृष्टि',
    readTime: 8,
    date: 'January 20, 2025',
    date_hi: '20 जनवरी, 2025',
    author: 'Rajesh Verma',
    author_hi: 'राजेश वर्मा',
    image: 'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['investment', 'comparison', 'wealth'],
  },
  {
    id: '5',
    title: 'Complete Guide to Plot Registration Process in Uttar Pradesh',
    title_hi: 'उत्तर प्रदेश में प्लॉट पंजीकरण प्रक्रिया की पूरी गाइड',
    slug: 'plot-registration-process-uttar-pradesh',
    excerpt: 'Step-by-step walkthrough of the plot registration process in UP — documents needed, stamp duty rates, online registration portal, and common mistakes to avoid.',
    excerpt_hi: 'यूपी में प्लॉट पंजीकरण प्रक्रिया की चरण-दर-चरण जानकारी — आवश्यक दस्तावेज, स्टांप शुल्क दरें, ऑनलाइन पंजीकरण पोर्टल और बचने योग्य सामान्य गलतियां।',
    category: 'Legal Guide',
    category_hi: 'कानूनी गाइड',
    readTime: 10,
    date: 'December 5, 2024',
    date_hi: '5 दिसंबर, 2024',
    author: 'Amit Tiwari',
    author_hi: 'अमित तिवारी',
    image: 'https://images.pexels.com/photos/1642125/pexels-photo-1642125.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['registration', 'legal', 'documentation'],
  },
  {
    id: '6',
    title: 'NRI Guide: How to Buy a Plot in India from Abroad',
    title_hi: 'एनआरआई गाइड: विदेशों से भारत में प्लॉट कैसे खरीदें',
    slug: 'nri-guide-buy-plot-india',
    excerpt: 'Everything an NRI needs to know about purchasing land in India — FEMA regulations, power of attorney, repatriation of funds, and our dedicated NRI assistance service.',
    excerpt_hi: 'भारत में भूमि खरीदने के बारे में एक एनआरआई को जानने योग्य सब कुछ — फेमा (FEMA) नियम, मुख्तारनामा (Power of Attorney), धन की वापसी, और हमारी समर्पित एनआरआई सहायता सेवा।',
    category: 'NRI Corner',
    category_hi: 'एनआरआई कोना',
    readTime: 9,
    date: 'November 10, 2024',
    date_hi: '10 नवंबर, 2024',
    author: 'Priya Singh',
    author_hi: 'प्रिया सिंह',
    image: 'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['nri', 'investment', 'legal'],
  },
];
